/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author ANGGAA
 */
public class viewMain extends javax.swing.JFrame {

    /**
     * Creates new form viewMain
     */
    public viewMain() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        this.btnBeef.setVisible(true);
        this.btnBeef.setOpaque(false);
        this.btnBeef.setContentAreaFilled(false);
        this.btnBeef.setBorderPainted(false);
        
        this.btnVegetables.setOpaque(false);
        this.btnVegetables.setContentAreaFilled(false);
        this.btnVegetables.setBorderPainted(false);
        
        this.btnBuy.setOpaque(false);
        this.btnBuy.setContentAreaFilled(false);
        this.btnBuy.setBorderPainted(false);
        
    }
    
    public void disableBuyStock(boolean a){
        this.btnBuy.setVisible(a);
    }
    
    public void addBuyListener(ActionListener listener){
        this.btnBuy.addActionListener(listener);
    }
    
    public void addBeefListener(ActionListener listener){
        this.btnBeef.addActionListener(listener);
    }
    
    public void addVegetablesListener(ActionListener listener){
        this.btnVegetables.addActionListener(listener);
    }
    //beef
    public void disableBeef(boolean a){
        this.btnBeef.setVisible(a);
        this.txtBeef.setText("");
    }
    
    public void setBeef(int customer){
        this.txtBeef.setText(String.valueOf(customer));
    }
    
    //vegetables
    public void disableVegetables(boolean a){
        this.btnVegetables.setVisible(a);
        this.txtVegetables.setText("");
    }
    
    public void setVegetables(int customer){
        this.txtVegetables.setText(String.valueOf(customer));
    }
    
    //uang nya
    public void setUang(double uang){
        this.txtUang.setText(String.valueOf(uang));
    }
    
    //tampilkan pesan
    public void showMessage(String pesan){
        JOptionPane.showMessageDialog(this, pesan, "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambarMain1 = new codingGambar.gambarMain();
        btnVegetables = new javax.swing.JButton();
        txtUang = new javax.swing.JLabel();
        btnBeef = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        txtVegetables = new javax.swing.JLabel();
        txtBeef = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gambarMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVegetables.setBackground(new java.awt.Color(51, 255, 51));
        gambarMain1.add(btnVegetables, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 353, 210, 52));

        txtUang.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtUang.setForeground(new java.awt.Color(204, 204, 0));
        gambarMain1.add(txtUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 409, 152, 32));

        btnBeef.setBackground(new java.awt.Color(255, 102, 102));
        gambarMain1.add(btnBeef, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 269, 210, 53));
        gambarMain1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 61, 126, 32));

        txtVegetables.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtVegetables.setForeground(new java.awt.Color(255, 255, 255));
        txtVegetables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambarMain1.add(txtVegetables, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 124, 44, 37));

        txtBeef.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtBeef.setForeground(new java.awt.Color(255, 255, 255));
        txtBeef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambarMain1.add(txtBeef, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 70, 44, 36));

        jLabel2.setText(" ");
        gambarMain1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 409, 210, -1));

        getContentPane().add(gambarMain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeef;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnVegetables;
    private codingGambar.gambarMain gambarMain1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtBeef;
    private javax.swing.JLabel txtUang;
    private javax.swing.JLabel txtVegetables;
    // End of variables declaration//GEN-END:variables
}
