/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author ANGGAA
 */
public class viewMain extends javax.swing.JFrame {

    /**
     * Creates new form viewMain
     */
    public viewMain() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        this.btnBeef.setVisible(true);
        this.btnBeef.setText("1");
    }
    
    public void disableBuyStock(boolean a){
        this.btnBuy.setVisible(a);
    }
    
    public void addBuyListener(ActionListener listener){
        this.btnBuy.addActionListener(listener);
    }
    
    public void addBeefListener(ActionListener listener){
        this.btnBeef.addActionListener(listener);
    }
    
    public void addVegetablesListener(ActionListener listener){
        this.btnVegetables.addActionListener(listener);
    }
    //beef
    public void disableBeef(boolean a){
        this.btnBeef.setVisible(a);
    }
    
    public void setBeef(int customer){
        this.btnBeef.setText(String.valueOf(customer));
    }
    
    //vegetables
    public void disableVegetables(boolean a){
        this.btnVegetables.setVisible(a);
    }
    
    public void setVegetables(int customer){
        this.btnVegetables.setText(String.valueOf(customer));
    }
    
    //uang nya
    public void setUang(double uang){
        this.txtUang.setText(String.valueOf(uang));
    }
    
    //tampilkan pesan
    public void showMessage(String pesan){
        JOptionPane.showMessageDialog(this, pesan, "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambarMain1 = new codingGambar.gambarMain();
        btnBuy = new javax.swing.JButton();
        btnBeef = new javax.swing.JButton();
        txtUang = new javax.swing.JLabel();
        btnVegetables = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuy.setText("BUY STOCK");

        btnBeef.setBackground(new java.awt.Color(255, 102, 102));

        txtUang.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        btnVegetables.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout gambarMain1Layout = new javax.swing.GroupLayout(gambarMain1);
        gambarMain1.setLayout(gambarMain1Layout);
        gambarMain1Layout.setHorizontalGroup(
            gambarMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarMain1Layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addGroup(gambarMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gambarMain1Layout.createSequentialGroup()
                        .addComponent(btnBuy)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gambarMain1Layout.createSequentialGroup()
                        .addGroup(gambarMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVegetables, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBeef, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212))))
            .addGroup(gambarMain1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gambarMain1Layout.setVerticalGroup(
            gambarMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarMain1Layout.createSequentialGroup()
                .addComponent(btnBuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnBeef, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnVegetables, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeef;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnVegetables;
    private codingGambar.gambarMain gambarMain1;
    private javax.swing.JLabel txtUang;
    // End of variables declaration//GEN-END:variables
}
